FROM golang AS builder2

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux
#    GOPROXY=https://mirrors.aliyun.com/goproxy/

WORKDIR /build
ADD go.mod go.sum ./
RUN go clean -modcache
RUN go mod download
COPY . .
COPY ./web/build ./web/build
RUN go build -ldflags "-s -w -X 'one-api/common.Version=$(cat VERSION)' -extldflags '-static'" -o one-api

FROM alpine

RUN apk update \
    && apk upgrade \
    && apk add --no-cache ca-certificates tzdata \
    && update-ca-certificates 2>/dev/null || true

COPY --from=builder2 /build/one-api /
EXPOSE 3001
WORKDIR /data
ENTRYPOINT ["/one-api"]
